name: Lint

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        run: pipx install poetry==1.8.3
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install Python dependencies
        run: poetry install --no-interaction --no-root
      - name: Install Project
        run: poetry install --no-interaction
      - name: Lint with Black
        run: poetry run black --check .
      - name: Lint with Flake8
        run: poetry run flake8 .
